n = input('Digite algo: ')
print('O tipo primitivo do valor digitado é ', type(n))
print('O valor digitado é numerico?', n.isnumeric())
print('O valor digitado é uma string?', n.isalpha())
print('O valor digitado é um numero/string?', n.isalnum())
print('O valor digitado é decimal?', n.isdecimal())
print('O valor digitado está capitalizado?', n.istitle())
print('O valor digitado é somente espaços?', n.isspace())
print('O valor digitado está em maiuscluas', n.isupper())
print('O valor digitado está em minusculas', n.islower())